[package]
name = "ddm_compression"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2", features = ["serde"] }
constriction = "0.5.0"
eframe = "0.36.2"
egui_plot = "0.37.0"
ndarray = "0.16.1"
osclet = "0.4.3"
proptest = "1.11.0"
serde = { version = "1.0.229", features = ["derive"] }
serde-big-array = "0.5.1"
zstd = "0.14.0"
